let current_q = 0;
let q_num;
let q_set;
var question = document.getElementById('question');
var choiceA = document.getElementById('choiceA');
var choiceB = document.getElementById('choiceB');
var choiceC = document.getElementById('choiceC');
var choiceD = document.getElementById('choiceD');
var feedback = document.getElementById('feedback');

let question_set1 = {
    q_num : 2,
    q_list : [
        {
            question : "A magnetic field can be created by which of the following?",
            choice_num : 4,
            is_multi : true,
            A : "Magnet",
            B : "Electricity",
            C : "Thermostat",
            D : "Iron",
            correct : ["A","B"],
            feedback : {
                correct : "Congratulations!",
                wrong : "Unfortunately, you didn't pick the right answer. That would be the right answer: Magnet, Electricity."
            }
        },{
            question : "Why would an induction cooker generate a magnetic field?",
            choice_num : 3,
            is_multi : false,
            A : "When the induction cooker is plugged in, the electric current running through the coil will create a magnetic field.",
            B : "There is a magnet in the induction cooker that can generate a magnetic field.",
            C : "Because the induction cooker is made of iron.",
            correct : "A",
            feedback : {
                
            }
        }
    ]
};

let question_set2 = {
    q_num : 3,
    q_list : [
        {
            question : "What kinds of energy does eddy current generate?",
            choice_num : 4,
            is_multi : false,
            A : "Thermal energy and electrical energy",
            B : "Thermal energy and chemical energy",
            C : "Thermal energy and mechanical energy",
            D : "Mechanical energy and electrical energy",
            correct : "A",
            feedback : {
                A : "Exactly. Eddy current generates thermal energy and electrical energy.",
                B : "Not quite right.",
                C : "Not quite right.",
                D : "Not quite right.",
            }
        },{
            question : "What creates an eddy current in the pot?",
            choice_num : 4,
            is_multi : false,
            A : "Magnetic field",
            B : "Electricity",
            C : "Fire",
            D : "Coil",
            correct : "A",
            feedback : {
                A : "Yes, The magnetic field generated by the induction cooker interacts with the pot and creates an eddy current in it.",
                B : "Try to think about what makes the induction cooker interact with the pot.",
                C : "Try to think about what makes the induction cooker interact with the pot.",
                D : "Not quite right, the coil is an essential part of the process, but it’s not interacting with the pot directly.",
            }
        },{
            question : "What kind of energy transfer happens when your cell phone gets warm as you constantly use it?",
            choice_num : 4,
            is_multi : false,
            A : "Thermal energy -> electrical energy",
            B : "Mechanical energy -> thermal energy",
            C : "Electrical energy -> Thermal energy",
            D : "Thermal energy -> chemical energy",
            correct : "C",
            feedback : {
                A : "Thermal energy is indeed involved because the cell phone becomes warm, but is it really at this end of the arrow?",
                B : "Thermal energy is exactly the one that gets transformed into, but is it mechanical energy that generates it?",
                C : "That’s right. The battery in the cell phone generates electrical energy, and it’s transformed into more and more thermal energy as you continue to use it.",
                D : "Thermal energy is indeed involved because the cell phone becomes warm, but is it really at this end of the arrow? What’s more, chemical energy is not involved in this process.",
            }
        }
    ]
};



// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement('script');

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var player1;
var player2;
var player3;
var player4;
function onYouTubeIframeAPIReady() {
  player1 = new YT.Player('player1', {
    height: '640',
    width: '900',
    videoId: 'vyiFCQ_dgFA',
    events: {
      'onReady': onPlayerReady,
      'onStateChange': onPlayerStateChange
    }
  });
  player2 = new YT.Player('player2', {
    height: '640',
    width: '900',
    videoId: 'WO24UVyO-tU',
    events: {
      'onReady': onPlayerReady,
      'onStateChange': onPlayerStateChange
    }
  });
  player3 = new YT.Player('player3', {
    height: '640',
    width: '900',
    videoId: 'NJChRtWnV4g',
    events: {
      'onReady': onPlayerReady,
      'onStateChange': onPlayerStateChange
    }
  });
  player4 = new YT.Player('player4', {
    height: '640',
    width: '900',
    videoId: 'CaDbU2UbD_s',
    events: {
      'onReady': onPlayerReady,
      'onStateChange': onPlayerStateChange
    }
  });
}
//
//function stopvideo(){
//    player.stopVideo();
//}

function onPlayerReady(event){
//    player.playVideo();
}

function onPlayerStateChange(event){
//    if (event.data == YT.PlayerState.ENDED) {
//      $('#player').fadeOut();
//    }
}

//function loadQuestions(q_set){
//    q_num = q_set.q_num;
//    
//}

function show_q(n){
    q_num = q_set.q_num;
//    console.log(n);
//    console.log(q_num);
//    console.log("loading")
    current_q = n;
    question.innerHTML = q_set.q_list[n].question;
    choiceA.innerHTML = q_set.q_list[n].A;
    choiceB.innerHTML = q_set.q_list[n].B;
    choiceC.innerHTML = q_set.q_list[n].C;
    choiceD.innerHTML = q_set.q_list[n].D;
    if (n >= q_num - 1) {
//        console.log("btn change")
        $('#next_q_btn').fadeOut();
        $('#discussion_btn').fadeIn();
    }
}

function next_q(){
    feedback.innerHTML = "";
    $('#feedback').removeClass('feedback_wrong');
    $('#feedback').removeClass('feedback_correct');
    show_q(current_q + 1);
    $(".option").removeClass('option_selected');
}

function checkAnswer(user_ans){
    console.log(user_ans);
    console.log(q_set.q_list[current_q].correct);
    if (user_ans == q_set.q_list[current_q].correct){
        $('#feedback').removeClass('feedback_wrong');
        $('#feedback').addClass('feedback_correct');
    }
    else {
        $('#feedback').removeClass('feedback_correct');
        $('#feedback').addClass('feedback_wrong');
    }
    switch(user_ans){
        case "A":
            feedback.innerHTML = q_set.q_list[current_q].feedback.A;
            break;
        case "B":
            feedback.innerHTML = q_set.q_list[current_q].feedback.B;
            break;
        case "C":
            feedback.innerHTML = q_set.q_list[current_q].feedback.C;
            break;
        case "D":
            feedback.innerHTML = q_set.q_list[current_q].feedback.D;
            break;
        default:
            feedback.innerHTML = "Ooops, can't find what to tell you."
    }
        
    
}

function timer(time, id){
    var x = setInterval(function(){
        time = time - 1;
        min = Math.floor(time/60);
        sec = time % 60;
        document.getElementById(id).innerHTML = min + ':' + sec;
    }, 1000)
}


function next(el){
    var next = $(el).data('next');
    $(el).parent().fadeOut();
    $(next).fadeIn();
}

$(document).ready(function(){
    $(".next_buttons").click(function(){
        next(this)
    });
    
    $(".next_buttons_link").click(function(){
        next(this)
    });
    
    $(".option").click(function(){
        $(".option").removeClass('option_selected');
        $(this).addClass('option_selected');
    })
    
    $(".next_assess").click(function(){
        var next = $(this).data('next');
        $(this).parent().fadeOut(function(){
        $("#assessment").fadeIn(function(){
            console.log(next);
            if (next.includes('assessment1')){
                player1.stopVideo(); 
                q_set = question_set1;
                show_q(current_q);
            };
            if (next.includes('assessment2')){
                player2.stopVideo();  
                q_set = question_set2;
                show_q(current_q);
            };
            if (next.includes('assessment3')){
                player3.stopVideo(); 
                q_set = question_set3;
                show_q(current_q);
            }
        });        
    });
    })
    
    $("#start_dis_timer").click(function(){
        $('#start_dis_timer').fadeOut();
        timer(900, 'timer');
    }
)
})

